### ISSUE TITLE
Adiciona amigos (front)

### ISSUE THREAD

**Issue by LiviaCavalcanti** [LiviaCavalcanti/contare#40]

**Comment by rafaelgdp** [comment]
Criei uma branch chamada friend-add para implementar as funcionalidades desta issue. Já upei um início do código que fiz ontem. Continuarei amanhã. Até agora criei um esboço da view e components para essa aba de amigos. A parte de listagem vai mudar bastante, creio.

**Comment by rafaelgdp** [comment]
Terminei boa parte desta task. Falta dar uma revisada na lógica do backend porque quando envia um addNewFriend lá na rota, o outro amigo já é adicionado automaticamente (sem nenhuma confirmação da outra parte). Mas já tá adicionando, validando se usuário existe, não é vc mesmo, e atualiza a lista de amigos na view. Só falta adicionar essa parte da confirmação. O real-time tá meio implementada no front já, falta ajeitar no back o evento no esquema do socket.io. Mais tarde eu dou uma olhada no real-time.
