### ISSUE TITLE
Tela de perfil

### ISSUE THREAD

**Issue by LiviaCavalcanti** [LiviaCavalcanti/contare#71]
- Desabilitar o campo do email para modificar
- Estilizar o botão de upload de foto
- Usar a foto do usuário no card dos amigos
- Remover listagem de redes sociais no card do usuario

**Comment by rafaelgdp** [comment]
Já desabilitei o campo de e-mail e fiz uns ajustes no backend para validar se o nome de usuário que se tenta editar está disponível ou não. Dessa forma, o back garante que ele é único para todos os usuários.

**Comment by rafaelgdp** [comment]
Já adicionei a foto do usuário nos cards da tela de amigos também. Está tudo na branch rafael-front.

**Comment by rafaelgdp** [comment]
Finalizado.
